version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    container_name: fullapp
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_DB=$PG_DB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
